"$schema" = 'https://starship.rs/config-schema.json'

format = '($username$hostname )$directory$git_branch$git_status$cmd_duration$line_break$character'
add_newline = true

[directory]
truncation_length = 0
truncate_to_repo = false
read_only = ' (read-only)'

[username]
format = '[$user]($style)'

[hostname]
format = '[@$hostname]($style)'
ssh_only = true

[git_branch]
format = '[$branch]($style) '

[git_status]
renamed = '~'
deleted = 'x'

[cmd_duration]
min_time = 2000
format = '[$duration]($style) '

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
